version: '3.8'

name: service-cache-container
services:
  app:
    image: 'quarkus/manager-service'
    container_name: "service-cache"
    ports:
      - '8080:8080'
    links:
      - "book-db"
    environment:
      - DB_USER=root
      - DB_PWD=root
      - DB_URL=jdbc:postgresql://localhost:5432/book

  book-db:
    image: postgres:15
    container_name: "book-db"
    environment:
      - POSTGRES_DB=book
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - '5432:5432'
    volumes:
      - manager:/var/lib/postgresql/data
      - ./../../../db/sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
volumes:
  manager:
    driver: local